# Generated by Django 3.2.3 on 2022-05-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('methane', 'Methane'), ('temperature', 'Temperature')], default='methane', max_length=12)),
                ('recorded', models.DateTimeField()),
            ],
        ),
    ]
