# Generated by Django 4.0.6 on 2022-07-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_gasreadingdata_humidityreading_temperaturereading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GasReadingData',
            new_name='GasReading',
        ),
    ]
