# Generated by Django 4.0.6 on 2022-07-18 22:01

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_rename_gasreadingdata_gasreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notepad',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='GasReading',
        ),
        migrations.DeleteModel(
            name='HumidityReading',
        ),
        migrations.DeleteModel(
            name='Methane',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
        migrations.DeleteModel(
            name='TemperatureReading',
        ),
        migrations.AlterModelOptions(
            name='readingdata',
            options={'ordering': ['-created'], 'verbose_name': 'Data Reading', 'verbose_name_plural': 'Data Readings'},
        ),
    ]
