# Generated by Django 4.0.6 on 2022-07-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0007_alter_notepad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_gas_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_gas_level', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
