# Generated by Django 4.0.6 on 2022-07-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0008_thresholdsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thresholdsettings',
            options={'verbose_name': 'Base Settings', 'verbose_name_plural': 'Base Settings'},
        ),
        migrations.AddField(
            model_name='notepad',
            name='note_type',
            field=models.CharField(choices=[('Accident', 'Accident'), ('Near-miss', 'Near-miss'), ('Hazard', 'Hazard'), ('General', 'General')], default='General', max_length=20),
        ),
    ]
